---


- name: Install minikube
  get_url: 
    url: "https://storage.googleapis.com/minikube/releases/{{ version }}/minikube-linux-amd64"
    dest: /usr/local/bin/minikube
    sha256sum: "{{ checksum }}"
    mode: '0755'
